version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kmd_web_app
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    networks:
      - kmd_default

networks:
  kmd_default:
    external: true
